export interface UserData {
  id: number;
  name: string;
  first_name: string;
  last_name: string;
  business_name: string | null;
  email: string;
  email_verified_at: string | null;
  two_factor_secret: string | null;
  two_factor_recovery_codes: string | null;
  address: string | null;
  address2: string | null;
  phone: string;
  birthday: any;
  city: string;
  state: string | null;
  country: string;
  zip_code: string | null;
  last_login_at: string | null;
  avatar_id: string | null;
  bio: string;
  status: string;
  review_score: number | null;
  create_user: number | null;
  update_user: number | null;
  vendor_commission_amount: number | null;
  vendor_commission_type: string | null;
  need_update_pw: number;
  role_id: number;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  payment_gateway: string | null;
  total_guests: number | null;
  locale: string | null;
  user_name: string | null;
  verify_submit_status: string | null;
  is_verified: boolean | null;
  active_status: number;
  dark_mode: number;
  messenger_color: string;
  stripe_customer_id: string | null;
  total_before_fees: number | null;
  credit_balance: number | null;
  avatar_url: string | null;
  address1: string;
  zip: string;
}
